name: frpc
icon: frpc
type: infrastructure
title: FRPC
helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/frpc
  chart: oci://registry-1.docker.io/wodby/frpc
  version: 0.1.0
  values:
  - name: frpc.name
    value: '{{kubernetes.fullName}}'
  - name: frpc.serverAddr
    value: '{{kubernetes.frpc.serverAddr}}'
  - name: frpc.serverPort
    value: '{{kubernetes.frpc.serverPort}}'
  - name: frpc.httpUser
    value: '{{kubernetes.frpc.httpUser}}'
  - name: frpc.httpPassword
    value: '{{kubernetes.frpc.httpPassword}}'
  - name: frpc.oidcTokenEndpointURL
    value: '{{kubernetes.frpc.oidcTokenEndpointURL}}'
  - name: frpc.oidcClientID
    value: '{{kubernetes.frpc.oidcClientID}}'
  - name: frpc.oidcClientSecret
    value: '{{kubernetes.frpc.oidcClientSecret}}'
  - name: frpc.customDomain
    value: '{{kubernetes.frpc.customDomain}}'
  - name: frpc.apiPrefix
    value: '/{{kubernetes.fullName}}/'
  - name: frpc.location
    value: '/{{kubernetes.fullName}}'

workloads:
- id: main
  kind: deployment
  primary: true
  helm:
    labels: podLabels
    annotations: podAnnotations
    volumes: extraVolumes
  containers:
  - name: frpc
    helm:
      env: envVars
      mounts: extraVolumeMounts
